version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    # Volumes ini biar lu tetep bisa ngedit kode sambil server jalan!
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules # Biar gak bentrok sama folder node_modules lokal
    depends_on:
      - backend